import './globals.css'
import { Inter } from 'next/font/google'
import HeaderWrapper from '../components/HeaderWrapper';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio de Zakaria Talali',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.documentElement.style.setProperty(
                '--scrollbar-width',
                (window.innerWidth - document.documentElement.clientWidth) + 'px'
              );
            `,
          }}
        />
      </head>
      <body className={inter.className}>
        <HeaderWrapper />
        {children}
      </body>
    </html>
  )
}
